---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://ansible.cc/docs/playbooks.html for more information about handlers.

- name: restart ssh
  service: name=ssh state=restarted

- name: restart ntp
  service: name=ntp state=restarted

