---
# [FIXME docs]
# Note: assumes the existence of a git repo for the contents of the site

- name: nginx site-available for {{ www_host }}
  template: src=nginx_static.j2 dest=/etc/nginx/sites-available/{{ www_host }}

- name: enable {{ www_host }}
  file: src=/etc/nginx/sites-available/{{ www_host }} dest=/etc/nginx/sites-enabled/{{ www_host }} state=link
  notify: restart nginx

