#!/bin/sh

AS_USER=sysadmin
LOG=/home/git/devops.log
SLINE="------------------------------------------------------------------------------"
DLINE="=============================================================================="

log() { echo "$@" } 2>&1
die() { log("$@"); exit 1; }

log(`/bin/date --utc`)
git push --mirror origin 2>&1
#/usr/bin/sudo /bin/su -l $AS_USER -c \
#    "/home/$AS_USER/WORKING/devops/puppet/puppet-exec.sh" >> $LOG 2>&1
log($DLINE)
log(`/bin/date --utc`)
log($SLINE)
