#!/bin/sh

AS_USER=sysadmin
LOG=/home/git/devops.log
SLINE="------------------------------------------------------------------------------"
DLINE="=============================================================================="

die() { echo "$@" >> $LOG; exit 1; } 2>&1

echo `/bin/date --utc` >> $LOG
/usr/bin/sudo /bin/su -l $AS_USER -c \
        "/home/$AS_USER/WORKING/devops/puppet/puppet-exec.sh" >> $LOG 2>&1
echo $DLINE >> $LOG
echo `/bin/date --utc` >> $LOG
echo $SLINE >> $LOG
