#!/bin/bash

exec git update-server-info

AS_USER=sysadmin
LOG=/home/git/DEVOPS.LOG
SLINE='------------------------------------------------------------------------------'
DLINE='=============================================================================='

log() { echo "$@" >> $LOG; } 2>&1
die() { logi "$@"; exit 1; }

log `/bin/date --utc`
git push --mirror origin >> $LOG 2>&1
#/usr/bin/sudo /bin/su -l $AS_USER -c \
#    "/home/$AS_USER/WORKING/devops/puppet/puppet-exec.sh" >> $LOG 2>&1
log $DLINE
log `/bin/date --utc`
log $SLINE
